---
title: Fundacja Nowe Teraz
timezone: Europe/Warsaw
collections:
  gallery:
    title: Biblioteka FNT
    output: true
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
  auctions:
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    image: 
    description: 
    button:
      title: 
      url: 
- scope:
    path: ''
    type: blog_tags
  values:
    layout: tag
- scope:
    path: ''
    type: gallery
  values:
    image: 
    link: 
url: https://www.noweteraz.pl
description: Edukujemy, wspieramy i inspirujemy wspólne działanie osób w trudnej sytuacji życiowej.
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- package-lock.json
- README*
- node_modules
- ".gitignore"

plugins:
- jekyll-seo-tag
- jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
excerpt_separator: |2+

sass:
  sass_dir: styles/
  style: compressed
per_page: 12
date_format: "%d-%m-%Y"
google_analytics: UA-133950974-1
twitter:
  username: 
logo: "/assets/logo-nowe-teraz-300x132.png"
future: true
header_nav:
  Strona główna: "/"
  Blog: "/blog/"
  Projekty: "/projekty/"
  Sklep: "/sklep-charytatywny/"
  Kontakt: "/kontakt/"
footer_nav:
  Strona główna: "/"
  Galeria: "https://galeria.noweteraz.pl"
  Sklep: "/sklep-charytatywny/"
  Polityka prywatności: "/polityka-prywatnosci/"
  Kontakt: "/kontakt/"
  
